language: python
python:
    "3.7.5"

stages:
    name: test
    name: deploy

jobs:
    include:
        stage: test
        name: Unit Tests
        script: python manage.py test
        stage: deploy
        name: Heroku Deploy
        script: /bin/true
        deploy:
            provider: heroku
            api_key: 
                secure: fb227e24-1f60-4597-9f6f-2556e619e341
            app: mfhorita
            on: master
            run: "python manage.py migrate"